// <auto-generated />
namespace Wpf_Navigation_1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ConnectionStr : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ConnectionStr));
        
        string IMigrationMetadata.Id
        {
            get { return "201907111440093_ConnectionStr"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
